[build]
  base    = "sandra-schartmueller"
  command = "pnpm exec ng build"
  publish = "dist/sandra-schartmueller/browser"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
